// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDWT7hxllVSqG2P-WHl9xjOlnKmak9gEuE',
    appId: '1:69545249274:web:4cc919b76f51374ead3c43',
    messagingSenderId: '69545249274',
    projectId: 'messageapp-c4b3b',
    authDomain: 'messageapp-c4b3b.firebaseapp.com',
    storageBucket: 'messageapp-c4b3b.firebasestorage.app',
    measurementId: 'G-RKCJV35F3T',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBm0KzvsdqcuFKEOLxBiAHGxFiNPVSCteg',
    appId: '1:69545249274:android:bc7a679da2fbc2dead3c43',
    messagingSenderId: '69545249274',
    projectId: 'messageapp-c4b3b',
    storageBucket: 'messageapp-c4b3b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAe05SAbwuWUWnpNuYEJQ4NXpNe_rpe6t4',
    appId: '1:69545249274:ios:9f87ba465e987e24ad3c43',
    messagingSenderId: '69545249274',
    projectId: 'messageapp-c4b3b',
    storageBucket: 'messageapp-c4b3b.firebasestorage.app',
    iosBundleId: 'com.example.messageApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAe05SAbwuWUWnpNuYEJQ4NXpNe_rpe6t4',
    appId: '1:69545249274:ios:9f87ba465e987e24ad3c43',
    messagingSenderId: '69545249274',
    projectId: 'messageapp-c4b3b',
    storageBucket: 'messageapp-c4b3b.firebasestorage.app',
    iosBundleId: 'com.example.messageApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDWT7hxllVSqG2P-WHl9xjOlnKmak9gEuE',
    appId: '1:69545249274:web:de180ba5bd33f6f1ad3c43',
    messagingSenderId: '69545249274',
    projectId: 'messageapp-c4b3b',
    authDomain: 'messageapp-c4b3b.firebaseapp.com',
    storageBucket: 'messageapp-c4b3b.firebasestorage.app',
    measurementId: 'G-2CG7WRBNFH',
  );
}